import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}
      //  style={{background: `linear-gradient(90deg, #FD00F3 0%, #1C4AC2 100%)`}}
      
       >{children}</body>
    </html>
  );
}



